### ISSUE TITLE
1440px未満のときに「今の座席」が想定通りに描画されていない

### ISSUE THREAD

**Issue by watsumi** [krpk1900/SekigaeMaker#239]
### 現状
PCで表示したときに、「今の座席」のカードが画面中央に表示されていない（画像１参照）。

多分サイドバーの下に描画されている？（画像２参照）

ちなみにタブレットでは正しく表示されていました！

（既に気づいていたらすみません。）

- 画像１
[![Image from Gyazo](https://i.gyazo.com/6bec64c033bc606e793bc34fa347fdea.png)](https://gyazo.com/6bec64c033bc606e793bc34fa347fdea)

- 画像２
[![Image from Gyazo](https://i.gyazo.com/0da3820574139db20f9e43d70f66821f.png)](https://gyazo.com/0da3820574139db20f9e43d70f66821f)

**Comment by krpk1900** [comment]
おー！！
気づいてなかったです！
内海さんどうもありがとうございます！

**Comment by krpk1900** [comment]
よく考えてみたら想定通りの挙動でした😂
1439px以下だったらタブレット横、1440以上だったらPCと判断してます！
PCでウィンドウ小さくして使うことって、僕の思ってる以上に多いですかねー？

**Comment by watsumi** [comment]
なるほど。
外部モニターで見てたので、1400pxでズレてたみたいです。

想定通りなら良かったですー🙆‍♂️

**Comment by krpk1900** [comment]
ちなみに外部モニタの解像度はどれくらいですかー？

**Comment by watsumi** [comment]
2560×1080ですー

**Comment by krpk1900** [comment]
でかいですね！笑
2560で見たときは崩れてないけれど、検証ツールで1439以下にすると崩れてしまうという認識で間違いないですよねー？

**Comment by watsumi** [comment]
でかいは正義なので。笑
ですです。

**Comment by krpk1900** [comment]
わざわざ教えてもらってありがとうございました！
